/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Shape;
import java.awt.Stroke;
import java.awt.geom.Line2D;
import java.awt.geom.Point2D;
import java.awt.image.BufferedImage;
import java.util.ArrayList;

/**
 *
 * @author josemlp
 */
public class GUILienzo extends javax.swing.JPanel {

    private BufferedImage img;
    private BufferedImage imgDest;

    static Stroke strok = new BasicStroke(10);
    static Color col;

    ArrayList<Shape> vShape = new ArrayList();
    public ArrayList<Point2D.Float> stars = new ArrayList();

    /**
     * Creates new form Lienzo
     */
    public GUILienzo() {

        initComponents();
        col = Color.RED;
        Point2D.Float p1 = new Point2D.Float(1148.f, 668.f);

       System.out.println(stars.size());
      
      
        for (Point2D.Float s : stars) {
            System.out.println("EEE");

            Line2D.Double punto = new Line2D.Double(s, s);
            vShape.add(punto);

        }

        Line2D.Double punto = new Line2D.Double(p1, p1);
        vShape.add(punto);

    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        Graphics2D g2d = (Graphics2D) g;
        if (imgDest != null) {
            g2d.drawImage(imgDest, 0, 0, this);
        }

        //Definimos el contexto.
        g2d.setPaint(col);
        g2d.setStroke(strok);

        //Bucle que pinta cada una de las figuras del array.
        for (Shape s : vShape) {
            g2d.fill(s);
            g2d.draw(s);
        }

    }

    public void setImageOriginal(BufferedImage img) {
        if (img != null) {
            setPreferredSize(new Dimension(img.getWidth(), img.getHeight()));
            this.img = img;
            setImageActual(img);
        }
    }

    void setImageActual(BufferedImage imgDest) {
        setPreferredSize(new Dimension(img.getWidth(), img.getHeight()));
        this.imgDest = imgDest;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
